POST http://localhost:3000/professionals/add
Content-Type: application/json

{
  "description":"test",
  "phone":"234",
  "latitude":"34243",
  "longitude":"23443",
  "userId":null
}

###
GET http://localhost:3000/professionals/
Content-Type: application/json

###
GET http://localhost:3000/professional/1
Content-Type: 'application/json; charset=utf-8'

